# -*- coding: utf-8 -*-
"""tp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/thomastosto/1a24a90ca1fc2b450ea0ff0e7a92adb1/tp2.ipynb
"""

# Exercice 1
import random
modalites=("Voiture","Moto","Velo","transport en commun","trottinette","A pied")
N=100
echantillon=random.choices(modalites,weights=[1,4,5,6,1,3],k=N)
#print(echantillon[:10]) test pour voir ce que ça donne
stat={} #set
# for elem in modalites:
#   ef=echantillon.count(lem)
for elem in modalites:
  stat[elem]=[]
for elem in stat.keys():
  stat[elem].append(echantillon.count(elem)) #effectif
  stat[elem].append(stat[elem][0]/N) #frequence
  stat[elem].append(stat[elem][1]*100) #freq en pourcentage
print(stat)
import matplotlib.pyplot as  plt
# Création du diagramme à bandes
effectifs = [stat[modalite][0] for modalite in modalites]
'''for elem in modalites
    ef=echantillon.count(elem)
    stat[elem]=[ef,ef/N,(ef/N)*100]
'''
plt.figure(figsize=(8, 4))  # Taille de la figure
plt.bar(modalites,effectifs, color='blue') # Création des barres
# Ajout de titres et labels
plt.title('Diagramme en barre')
plt.ylabel ("les effectifs ni")
plt.xticks(range(len(modalites))) # plt.xticks(np.arange(len(N)),modalites)
# Affichage du diagramme
plt.show()
#-------------------------------------------------
# Diag ciruclaire

# Création du diagramme circulaire
'''plt.figure(figsize=(8, 4))  # Taille de la figure
plt.pie(echantillon,pourcentage= for modalite in modalites,autopct='%d') # création du camembert
'''
plt.pie(effectifs, labels=modalites, autopct='%1.1f%%', startangle=140)
# Ajout du titre
plt.title('Un titre de votre choix')
# Affichage du diagramme
plt.show()

#-------------------------------------
#Exercice 2
N=500
#1) Le mode est Les films d'Action.
tab={'Action':(45/100)*500,'Comédie':(16/100)*500,'Sf':(22.2/100)*500,'Drame':(8.0/100)*500,'Comedie':16.0*5}
# effectifs =tab.count(element)
# for elem in modalites
#     ef=tab.count(elem)
#     stat[elem]=[ef,ef/N,(ef/N)*100]
# plt.figure(figsize=(8, 4))  # Taille de la figure
# plt.bar(modalites,effectifs, color='red') # Création des barres
# # Ajout de titres et labels
# plt.title('Diagramme en barre')
# plt.ylabel ("les effectifs ni")
# plt.xticks(range(len(modalites))) # plt.xticks(np.arange(len(N)),modalites)
# # Affichage du diagramme
# plt.show()